format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
truncation_length = 2
truncation_symbol = '.../'
truncate_to_repo = false
